runtime: nodejs20

env_variables:
  GEMINI_API_KEY: 'AIzaSyAZaiXjFpj9dtcxR4kKt7DuQBeszLm9ZMw'

handlers:
- url: /api/generate
  script: auto

- url: /(.*\.(css|js|png|jpg|jpeg|gif|svg|ico))$
  static_files: \1
  upload: .*\.(css|js|png|jpg|jpeg|gif|svg|ico)$

- url: /.*
  script: auto
